# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tactical_stream.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tactical_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15tactical_stream.proto\x12\x0etacticalstream\"\x8e\x01\n\x13TacticalObservation\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x12\n\nposition_x\x18\x02 \x01(\x02\x12\x12\n\nposition_y\x18\x03 \x01(\x02\x12\x10\n\x08velocity\x18\x04 \x01(\x02\x12\x12\n\nheart_rate\x18\x05 \x01(\x02\x12\x16\n\x0eteam_formation\x18\x06 \x03(\x02\"]\n\x10TacticalResponse\x12\x18\n\x10suggested_action\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x1b\n\x13predicted_positions\x18\x03 \x03(\x02\x32\xcb\x01\n\x0bMARLService\x12\\\n\x13PredictTacticalMove\x12#.tacticalstream.TacticalObservation\x1a .tacticalstream.TacticalResponse\x12^\n\x11StreamPredictions\x12#.tacticalstream.TacticalObservation\x1a .tacticalstream.TacticalResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tactical_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TACTICALOBSERVATION']._serialized_start=42
  _globals['_TACTICALOBSERVATION']._serialized_end=184
  _globals['_TACTICALRESPONSE']._serialized_start=186
  _globals['_TACTICALRESPONSE']._serialized_end=279
  _globals['_MARLSERVICE']._serialized_start=282
  _globals['_MARLSERVICE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
