# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tactical_stream_pb2 as tactical__stream__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tactical_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MARLServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictTacticalMove = channel.unary_unary(
                '/tacticalstream.MARLService/PredictTacticalMove',
                request_serializer=tactical__stream__pb2.TacticalObservation.SerializeToString,
                response_deserializer=tactical__stream__pb2.TacticalResponse.FromString,
                _registered_method=True)
        self.StreamPredictions = channel.stream_stream(
                '/tacticalstream.MARLService/StreamPredictions',
                request_serializer=tactical__stream__pb2.TacticalObservation.SerializeToString,
                response_deserializer=tactical__stream__pb2.TacticalResponse.FromString,
                _registered_method=True)


class MARLServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PredictTacticalMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPredictions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MARLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictTacticalMove': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictTacticalMove,
                    request_deserializer=tactical__stream__pb2.TacticalObservation.FromString,
                    response_serializer=tactical__stream__pb2.TacticalResponse.SerializeToString,
            ),
            'StreamPredictions': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredictions,
                    request_deserializer=tactical__stream__pb2.TacticalObservation.FromString,
                    response_serializer=tactical__stream__pb2.TacticalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tacticalstream.MARLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tacticalstream.MARLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MARLService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictTacticalMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tacticalstream.MARLService/PredictTacticalMove',
            tactical__stream__pb2.TacticalObservation.SerializeToString,
            tactical__stream__pb2.TacticalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPredictions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tacticalstream.MARLService/StreamPredictions',
            tactical__stream__pb2.TacticalObservation.SerializeToString,
            tactical__stream__pb2.TacticalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
